### ISSUE TITLE
npm publishing

### ISSUE THREAD

**Issue by stillonearth** [zalo/mujoco_wasm#7]
Hi,

seems this is far behind than initial demo. I can transfer you rights for npm's mujoco_wasm if you want to publish this

**Comment by zalo** [comment]
@stillonearth Sure; I can publish this if you like.

Thank you for the excellent foundation!   Emscripten/Build Toolchains still scare me 🙃

**Comment by stillonearth** [comment]
I've transferred rights to https://www.npmjs.com/~zalo

Feel free to close the issue if that's ok

**Comment by zalo** [comment]
@stillonearth I don't own that account!

Is it too late to transfer it to https://www.npmjs.com/~makeshifted ?

**Comment by stillonearth** [comment]
I've transferred to a correct one. Pls check.

**Comment by zalo** [comment]
Perfect; thank you!
