### ISSUE TITLE
Demo not working in firefox 78.2.0esr

### ISSUE THREAD

**Issue by jumpjack** [zalo/mujoco_wasm#8]
https://zalo.github.io/mujoco_wasm/

Uncaught SyntaxError: await is a reserved identifier[main.js:10:1](https://zalo.github.io/mujoco_wasm/examples/main.js)

But it works in Edge.

**Comment by zalo** [comment]
Sorry, must have been an old bug; should work now.

**Comment by jumpjack** [comment]
The erorr persists, and I see no changes in line 10 of  main.js  .

But probably my Firefox version is too ancient... and I cannot update it on this machine.

**Comment by jumpjack** [comment]
The erorr persists, and I see no changes in line 10 of  main.js  .

But probably my Firefox version is too ancient... and I cannot update it on this machine.

**Comment by zalo** [comment]
Interesting... if I were using ESBuild in this project, I could probably transpile it to older browsers... though the error it's giving suggests that it is incompatible with the WASM loading mechanism (or even `async` in general) which could make this pretty hard to port.
