### ISSUE TITLE
Cassie, Hand and Mug do not load in the demo 

### ISSUE THREAD

**Issue by Vittorio-Caggiano** [zalo/mujoco_wasm#9]
Hi, really cool work!

I played with the online demo https://zalo.github.io/mujoco_wasm/ on safari (16.3) + chrome (112.0.5615.49) and I noticed that the Cassie, Hand and Mug mujoco models are not shown. 

Do they work only in specific browsers e.g. firefox?

**Comment by zalo** [comment]
Oops, nope, there was a residual broken function from a recent refactor to use properties instead of getter methods; somehow these functions must have escaped my notice...

Should be fixed in a few minutes when the GH Pages rebuilds.
